# Spring Configuration
spring:
  application:
    name: user
  datasource:
    url: jdbc:h2:mem:mujiki
    username: mujiki_db
    password: nothing
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:logs/db.changelog-master.xml
    enabled: true

# API Configuration
api:
  endpoint:
    base-url: /api

# Feign Client Configuration
feign:
  client:
    config:
      default:
        logger:
          level: full
        request:
          timeout: 5000
        connect-timeout: 5000
        read-timeout: 5000

# Server Configuration
server:
  error:
    whitelabel:
      enabled: false
  port: 81
