# Spring Configuration
spring:
  application:
    name: user
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mujiki
    username: mujiki_db
    password: nothing

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:logs/db.changelog-master.xml
    enabled: true

# API Configuration
api:
  endpoint:
    base-url: /api


# Server Configuration
server:
  error:
    whitelabel:
      enabled: false
  port: 81
